version: "3.5"

services:

  postgres:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  core:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - keycloak
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  #  zookeeper:
  #    image: confluentinc/cp-zookeeper:7.1.1
  #    environment:
  #      ZOOKEEPER_CLIENT_PORT: 2181
  #      ZOOKEEPER_TICK_TIME: 2000
  #    ports:
  #      - "22181:2181"
  #
  #  kafka:
  #    image: confluentinc/cp-kafka:7.1.1
  #    depends_on:
  #      - zookeeper
  #    ports:
  #      - "29092:29092"
  #    environment:
  #      KAFKA_BROKER_ID: 1
  #      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  keycloak:
    image: jboss/keycloak:13.0.0
    environment:
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_IMPORT=/imports/realm-export.json
      - DB_VENDOR=h2
      - KEYCLOAK_URL=http://localhost:8080
      - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
    ports:
      - "9990:8080"
    depends_on:
      - postgres
